spring:
  application:
    name: "M-Bank"
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/m_bank
    username: postgres
    password: postgres
    hikari:
      schema: public
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 3600000  # 1 hour for not active connection
      max-lifetime: 7200000  # max time for active connection
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        default_schema: public
        jdbc:
          batch_size: 20
          batch_versioned_data: true
          order_inserts: true
          order_updates: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  writer-with-default-pretty-printer: true
#  default-produces-media-type: application/json
#  default-consumes-media-type: application/json

jwt:
  secret: my-secret
  lifetime: 30m